language: node_js

cache: yarn

services:
  - postgresql

addons:
  postgresql: 9.4

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/config.json.travis config/config.json

scripts:
  - yarn test
